### ISSUE TITLE
Add support for SEO title in index page

### ISSUE THREAD

**Issue by Eldenroot** [lukasamd/MyBB-SEO_Titles#3]

**Comment by Eldenroot** [comment]
Thank you! @lukasamd - I will try and le you know my other ideas. I had been using MySEO plugin with Gogle SEO.

Unfortunately, or maybe it is good, MySEO is really bugged but has many features which are needed nowadays. Can you check it yourself and add more improvements which are must have or should I write them to you by myself?

**Comment by lukasamd** [comment]
Ok, I will check MyBB SEO and maybe add something else.
I think too many options aren't good and decided last time to remove in near future e.x. Google SEO from my board. Preety links are not important thing for SEO - better idea is to add metas and create HTML5 templates (using tags like article, section, header, footer, time itp.).

**Comment by Eldenroot** [comment]
I agree with you. Your plugin is much better and bug free. I use your plugin together with Google SEO mod. 

Here is the link for MySEO: https://community.mybb.com/thread-166864.html

Some of the features are really nice and I miss them, but maybe in futute will be added by you, who knows. Thank you again!
